### PR TITLE
Added learning outcome policy, resolved #20

### LINKED ISSUE #20: Add a page for Learning Outcomes
Add a dedicated markdown file for the learning outcomes listed in the syllabus and make it in an easy-to-read format. README should have a link to the learning outcomes file.

### PR DESCRIPTION
**Pull request by piradeepan**

### CODE REVIEW

**Comment by kbuffardi** [comment]
Markdown file looks good, but let's link to it from README.md with a link titled "Learning Outcomes" (and don't forget to close the issue with keywords in your commit message)

**Comment by piradeepan** [comment]
Updated the README file

**Comment by piradeepan** [comment]
Updated

**Review by piradeepan — COMMENTED** [review]
Updated the file and README file again

**Comment by kbuffardi** [comment]
For consistency's sake, let's name the file with .md instead of .markdown

**Pull request merged**
