### PR TITLE
x02-SOLID- Single Responsibility Principle

### PR DESCRIPTION
**Pull request by Jayesh-sathe**

### CODE REVIEW

**Review by kbuffardi — CHANGES_REQUESTED** [review]
Thanks for the PR. There are some issues though. 

- [ ] Your PR includes changes to `Late Work Policy.md`, and `README.md` and include some erroneous code. The latter in particular still has conflict annotations that haven't been resolved. Ultimately, the PR shouldn't include changes to these files at all, unless it's just a new link to your SRP documentation.
- [x] The files you created are in the `design-patterns` folder but that is meant for other assignments in the future. Let's create a new folder called `design-principles` and put your image and .md file in there.

**Comment by Jayesh-sathe** [comment]
Hello Kevin,

Thank you on  your inputs.
I would make the necessary changes and commit back.

Thank You.
Regards,
Jayesh Sathe

**Comment by kbuffardi** [comment]
It looks like you fixed the second requested change but not the first:

- [ ] Your PR includes changes to `Late Work Policy.md`, and `README.md` and include some erroneous code. The latter in particular still has conflict annotations that haven't been resolved. Ultimately, the PR shouldn't include changes to these files at all, unless it's just a new link to your SRP documentation.

**Comment by Jayesh-sathe** [comment]
Removed merge conflict in Late work policy file

**Comment by kbuffardi** [comment]
`Late Work Policy.md` should be [unstaged](https://docs.gitlab.com/ee/university/training/topics/unstage.html) since it does not pertain to this commit

**Comment by Jayesh-sathe** [comment]
Removed Conflicts

**Pull request merged**
