### PR TITLE
+x03: Liskov Substitute Principle

### PR DESCRIPTION
**Pull request by nshaikh1**

### CODE REVIEW

**Comment by kbuffardi** [comment]
Please list each of your full names in one place so it is easy to quickly find who contributed to it.

Also, let's put the file within a `design-principles` folder instead of `Liskov Substitute Principle`

**Comment by nshaikh1** [comment]
Changes done, and moved to folder /design_principles

**Comment by kbuffardi** [comment]
[Unstage](https://docs.gitlab.com/ee/university/training/topics/unstage.html) the folder and files in `Liskov Substitute Principle`

**Comment by nshaikh1** [comment]
Okay, done. Check now!

**Pull request merged**
